# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7b3f5d27cc5bf6057a3624e505d39cf3811975b9130adb007175c837ea6c2539ccd0f5e8b48630a9ecc99e66ccc2a71d832cca3056b7f94d1897773f74f3021

test:
  secret_key_base: ee914d635c65579ff509a1a29f4cea0a09b34e09886232f48e2656730d94ddd7b8e271c5d8e2e377fd78ac9704206140b9ef0ac64aeb9841bcd057b3d23982d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
